
spring:
  profiles:
    active: develop
  datasource:
    #数据源
    name: test
    url: jdbc:mysql://39.97.214.57:3306/gradefour?serverTimezone=GMT%2b8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  #mapper.xml路径
  mapper-locations: classpath:/mapper/*.xml
  #实体类路径mapper中可以不用写全路径
  type-aliases-package: com.oupu.gradefour.entity
  configuration:
    default-statement-timeout: 30

