
spring:
  profiles:
    active: develop
  datasource:
    #数据源
    url: jdbc:mysql://39.97.214.57:3306/gradefour?serverTimezone=GMT%2b8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  #mapper.xml路径
  mapper-locations: classpath:/mapper/*.xml
  #mapper中resultType可以只写类名
  type-aliases-package: com.oupu.gradefour.entity
  #控制台打印mybatis sql
logging:
   level:
    com.oupu.gradefour.dao: debug

