spring:
  datasource:
    #数据源
    url: jdbc:mysql://39.97.314.57/gradefour
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  profiles:
    active: develop
mybatis:
  #mapper.xml路径
  mapper-locations: classpath:/mapper/*.xml
  #实体类路径mapper中可以不用写全路径
  type-aliases-package: com.oupu.gradefour.entity

